
pipeline_name: table_recognition

use_layout_detection: True
use_doc_preprocessor: True
use_ocr_model: True

SubModules:
  LayoutDetection:
    module_name: layout_detection
    model_name: RT-DETR-H_layout_3cls
    model_dir: null
    batch_size: 1

  TableStructureRecognition:
    module_name: table_structure_recognition
    model_name: SLANet_plus
    model_dir: null
    batch_size: 1

SubPipelines:
  DocPreprocessor:
    pipeline_name: doc_preprocessor
    use_doc_orientation_classify: True
    use_doc_unwarping: True
    SubModules:
      DocOrientationClassify:
        module_name: doc_text_orientation
        model_name: PP-LCNet_x1_0_doc_ori
        model_dir: null
        batch_size: 1
      DocUnwarping:
        module_name: image_unwarping
        model_name: UVDoc
        model_dir: null
        batch_size: 1
  GeneralOCR:
    pipeline_name: OCR
    text_type: general
    SubModules:
      TextDetection:
        module_name: text_detection
        model_name: PP-OCRv4_server_det
        model_dir: null
        batch_size: 1    
      TextRecognition:
        module_name: text_recognition
        model_name: PP-OCRv4_server_rec
        model_dir: null
        batch_size: 1
